language: c

sudo: false

env:
  - MINICONDA_VERSION=4.5.4
  - CONDA_DIR=$HOME/miniconda3
  - CONDA_PREFIX=$HOME/miniconda3
  - PATH=$CONDA_PREFIX/bin:$PATH

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/download
    - $CONDA_DIR/pkgs

before_install:
  - |-
    set -ex && \
    mkdir -p ${HOME}/download && \
    cd ${HOME}/download && \
    wget -N --quiet https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh && \
    echo "a946ea1d0c4a642ddf0c3a26a18bb16d *Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh" | md5sum -c - && \
    /bin/bash Miniconda3-${MINICONDA_VERSION}-Linux-x86_64.sh -f -b -p $CONDA_DIR \
  - |-
    $CONDA_DIR/bin/conda config --system --prepend channels conda-forge && \
    $CONDA_DIR/bin/conda config --system --set auto_update_conda false && \
    $CONDA_DIR/bin/conda config --system --set show_channel_urls true
  - $CONDA_DIR/bin/conda install --quiet --yes conda="${MINICONDA_VERSION%.*}.*"
  - $CONDA_DIR/bin/conda update --all --quiet --yes

install:
  - $CONDA_DIR/bin/python setup.py sdist
  - $CONDA_DIR/bin/python setup.py bdist_wheel
  - $CONDA_DIR/bin/conda env update -n root -f environment.yml
  - $CONDA_DIR/bin/python -m pip install -r requirements.txt
  - $CONDA_DIR/bin/python -m ipython profile create default
  - $CONDA_DIR/bin/importnb-install
  - $CONDA_DIR/bin/python -c "__import__('importnb.utils.ipython').utils.ipython.install('pidgin')"
  - $CONDA_DIR/bin/python -m pip install dist/deathbeds-*.tar.gz --ignore-installed --no-deps

script:
# on a branch only the notebook on the branch should run; on master everything.
- ls deathbeds/*.ipynb | xargs $CONDA_DIR/bin/python -m jupyter nbconvert --execute --ExecutePreprocessor.kernel_name=python --to notebook

deploy:
  provider: pypi
  user: docfast
  password:
    secure: 2Xv4H56OlSdei4p6BzW8b8RYtou4yihEWBzV4iAVqytu/T1Of3KKb3kwNW9Oqs4NzIRR077xJhEn8SP0PmIWYrGAH6l6hjf2copJcMzq4DPMEECUbGkADcbWAOhi3PIY2UD1xoAkTwQoP8rm6yMez+zfakpej7p1M47Zi01shHVsUTUshAa0VLukZJcDcfrDEOfeNZ+UifFII6ET9BMFEqJ0p62gJQnwu7TOknbYJi6iEbbksdhJRx25ezCauqJLRG0SOKF6NN4J+AUrAep9rmACDSX5OhptI5VcgpztDDkfbIow0P4QzkW1g5W/18iZoLDjBVk9iUKq99OHykj7Au90PZofRq6Ow1ysmvi7FZM4p4VGehlbTMxfnVAfcnnf7tGfrx+6dArDh4rlvMBAHS7N96LKHlQZ3jbK3SQo+CJcPxkENb7DvgprQgw/Mj35Cxt36P3FeJqPrd2MVZ2SMSO65Exca36GCkM7FT3KRKDPjkVrrhmT2p6g0bAduccW5ShYOzmDNLjP4+osbdjKjV00V7rLzaZtYt9q3zHJv0hJewJWNYBCZsMK78BGtL3iBh300VS4QKdLV+ZxrvmJQB1xb1nBklGg7LHYRdslwLtxZyNeUR0Sj0dTzDxuCgFx0e/NUfK975HUsZ69YWLqVpW9YIhSoW+r7+KNCxxsZeo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: deathbeds/deathbeds.github.io
