name: deathbeds

channels:
  - conda-forge
  - defaults

dependencies:
  - antlr >=4,<5
  - antlr-python-runtime >=4,<5
  - bokeh
  - bqplot
  - cadquery
  - click
  - datashape
  - freecad
  - giflib
  - importnb
  - ipyleaflet
  - ipyvolume
  - ipywidgets
  - jupyterlab >=0.32,<0.33
  - libpng
  - matplotlib
  - monkeytype
  - nbdime
  - networkx
  - nodejs >=8,<9
  - notebook
  - pandas
  - pygraphviz
  - python >=3.6,<3.7
  - pythreejs
  - retype
  - scikit-image
  - seaborn
  - setuptools
  - shapely
  - sympy
  - toolz
  - typed-ast
  - xlrd
  - rise
  - pip:
    - poser
