name: _surface-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - bqplot
  - ipyleaflet
  - ipyvolume
  - ipywidgets
  - jupyterlab
  - pythreejs
  - vaex
  - pip:
    - jupyterlab-discovery
    - rise
    - https://github.com/deathbeds/XXX/archive/1d0470d0771739988e27acc4981fe26969ea1471.tar.gz
