name: _surface-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - antlr >=4,<5
  - antlr-python-runtime >=4,<5
  - bokeh
  - click
  - giflib
  - jupyterlab_launcher
  - libpng
  - matplotlib
  - networkx
  - nodejs
  - notebook
  - pandas
  - pygraphviz
  - python >=3.6,<3.7
  - seaborn
  - setuptools
  - typed-ast
  - pip:
    - monkeytype
    - retype
    - https://github.com/deathbeds/aye/archive/master.tar.gz
    - https://github.com/sympy/sympy/archive/master.tar.gz
