name: _surface-dev

channels:
  - conda-forge
  - defaults

dependencies:
  - bqplot
  - ipyleaflet
  - ipyvolume
  - ipywidgets
  - jupyterlab
  - pythreejs
  - vaex
  - jupyter-themes
  - jupyter_contrib_nbextensions
  - pip:
    - jupyterlab-discovery
    - rise
    - https://github.com/deathbeds/XXX/archive/master.tar.gz
