#!/usr/bin/env bash
set -ex

python -m pip install -r requirements-git.txt --no-deps --ignore-installed

for ext in $(cat labextensions.txt)
do
  jupyter labextension install --no-build $ext
done
jupyter lab build --dev
jupyter labextension list | sort
